//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_ngvrmanager : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean TriggerClick
        {
            get
            {
                return SteamVR_Actions.ngvrmanager_TriggerClick;
            }
        }
        
        public virtual SteamVR_Action_Single TriggerPull
        {
            get
            {
                return SteamVR_Actions.ngvrmanager_TriggerPull;
            }
        }
        
        public virtual SteamVR_Action_Boolean Grip
        {
            get
            {
                return SteamVR_Actions.ngvrmanager_Grip;
            }
        }
        
        public virtual SteamVR_Action_Boolean TouchpadTouching
        {
            get
            {
                return SteamVR_Actions.ngvrmanager_TouchpadTouching;
            }
        }
        
        public virtual SteamVR_Action_Vector2 TouchpadTouchpoint
        {
            get
            {
                return SteamVR_Actions.ngvrmanager_TouchpadTouchpoint;
            }
        }
        
        public virtual SteamVR_Action_Boolean MenuClick
        {
            get
            {
                return SteamVR_Actions.ngvrmanager_MenuClick;
            }
        }
        
        public virtual SteamVR_Action_Boolean TouchpadClick
        {
            get
            {
                return SteamVR_Actions.ngvrmanager_TouchpadClick;
            }
        }
        
        public virtual SteamVR_Action_Boolean PrimaryButton
        {
            get
            {
                return SteamVR_Actions.ngvrmanager_PrimaryButton;
            }
        }
        
        public virtual SteamVR_Action_Boolean SecondaryButton
        {
            get
            {
                return SteamVR_Actions.ngvrmanager_SecondaryButton;
            }
        }
        
        public virtual SteamVR_Action_Boolean SecondaryTouchpadTouching
        {
            get
            {
                return SteamVR_Actions.ngvrmanager_SecondaryTouchpadTouching;
            }
        }
        
        public virtual SteamVR_Action_Vector2 SecondaryTouchpadTouchpoint
        {
            get
            {
                return SteamVR_Actions.ngvrmanager_SecondaryTouchpadTouchpoint;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.ngvrmanager_Haptic;
            }
        }
    }
}
